apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pedido-deployment
spec:
  template:
    metadata:
      name: app-pedido
      labels:
        app: app-pedido
    spec:
      containers:
        - name: app-container
          image: gabccardoso/pedido:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: 1000m
  replicas: 3
  selector:
    matchLabels:
      app: app-pedido